import nodemailer from 'nodemailer'

export interface ShiftVarianceEmailPayload {
  cashierName: string
  registerId: string
  storeId: string
  expected: number
  actual: number
  variance: number
  openTime?: string | Date
  closeTime?: string | Date
}

export async function sendVarianceAlert(
  recipients: string[],
  payload: ShiftVarianceEmailPayload,
  smtpConfig: { host: string; port: number; user: string; pass: string; from: string }
): Promise<{ ok: boolean; error?: string }> {
  if (!smtpConfig.user || !smtpConfig.pass || recipients.length === 0) {
    return { ok: false, error: 'SMTP not configured or no recipients' }
  }

  const transporter = nodemailer.createTransport({
    host: smtpConfig.host,
    port: smtpConfig.port,
    secure: false,
    auth: { user: smtpConfig.user, pass: smtpConfig.pass },
  })

  const sign = payload.variance < 0 ? '-' : '+'
  const abs = Math.abs(payload.variance).toFixed(2)
  const subject = `⚠️ Cash Drawer Variance: ${sign}$${abs} — Register ${payload.registerId}`

  const html = `
<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
  <div style="background:#1e2a3a;padding:20px;border-radius:8px 8px 0 0">
    <h2 style="color:#fff;margin:0;font-size:18px">⚠️ Cash Drawer Variance Detected</h2>
  </div>
  <div style="background:#f9fafb;padding:24px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px">
    <table style="width:100%;border-collapse:collapse;margin-bottom:20px">
      <tr><td style="padding:8px 12px;background:#fff;border:1px solid #e5e7eb;font-weight:600;color:#374151">Cashier</td><td style="padding:8px 12px;border:1px solid #e5e7eb">${payload.cashierName}</td></tr>
      <tr><td style="padding:8px 12px;background:#fff;border:1px solid #e5e7eb;font-weight:600;color:#374151">Register</td><td style="padding:8px 12px;border:1px solid #e5e7eb">${payload.registerId}</td></tr>
      <tr><td style="padding:8px 12px;background:#fff;border:1px solid #e5e7eb;font-weight:600;color:#374151">Expected Cash</td><td style="padding:8px 12px;border:1px solid #e5e7eb">$${payload.expected.toFixed(2)}</td></tr>
      <tr><td style="padding:8px 12px;background:#fff;border:1px solid #e5e7eb;font-weight:600;color:#374151">Actual Cash</td><td style="padding:8px 12px;border:1px solid #e5e7eb">$${payload.actual.toFixed(2)}</td></tr>
      <tr style="background:${payload.variance < 0 ? '#fef2f2' : '#fffbeb'}">
        <td style="padding:8px 12px;border:1px solid #e5e7eb;font-weight:700;color:#374151">Variance</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;font-weight:700;color:${payload.variance < 0 ? '#dc2626' : '#d97706'}">${sign}$${abs}</td>
      </tr>
    </table>
    <p style="font-size:12px;color:#6b7280;margin:0">This alert was automatically generated by NovaPOS. Please review the register report for this shift.</p>
  </div>
</div>`

  try {
    await transporter.sendMail({ from: smtpConfig.from || smtpConfig.user, to: recipients.join(','), subject, html })
    return { ok: true }
  } catch (err) {
    return { ok: false, error: String(err) }
  }
}
